version: '2.4'
services:
  #Service for nameserver
  namesrv:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
      - ./data/namesrv/store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
      - rocketmq

  #Service for broker
  broker:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911 
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - MAX_POSSIBLE_HEAP=209715200
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.5.1/conf/broker.conf
    command: sh mqbroker -c ../conf/broker.conf
    networks:
      - rocketmq

  #Service for another broker -- broker1
  broker1:
    image: rocketmqinc/rocketmq:4.5.1
    container_name: rmqbroker1
    links:
      - namesrv
    ports:
      - 10919:10919
      - 10921:10921 
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - MAX_POSSIBLE_HEAP=209715200
    volumes:
      - ./data1/broker/logs:/home/rocketmq/logs
      - ./data1/broker/store:/home/rocketmq/store
      - ./data1/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.5.1/conf/broker.conf
    command: sh mqbroker -c ../conf/broker.conf
    networks:
      - rocketmq

  console:
    image: ahrievil/rocketmq-console-ng:1.0.0
    container_name: rocketmqConsole
    ports:
     - 19000:8080
    environment:
      JAVA_OPTS: -Drocketmq.config.namesrvAddr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Drocketmq.config.loginRequired=true -Drocketmq.config.dataPath=/root/data
    volumes:
      - ./data/console/logs:/root/logs
      - ./data/console/store:/root/store
      - ./data/console/data:/root/data
    links:
     - namesrv:namesrv
     - broker:broker
     - broker1:broker1
    networks:
      - rocketmq

networks:
  rocketmq:
    name: rocketmq
    ipam:
      config:
        - subnet: 172.31.0.0/16
          # gateway: 172.31.0.1
